# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ensemble IISc
email: ensemble.iisc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The official site for Ensemble, the UG Physics Club of IISc Bangalore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ensemble.iisc.ac.in" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  - README.md

excerpt_separator: <!--more-->

collections:
  # posts:
  #   output: true
  #   permalink: /:categories/:year/:month/:day/:title/
  lectures:
    output: true
    permalink: /lectures/:path/
  events:
    output: true
    # permalink: /events/:title/

defaults:
  - scope:
      path: "_lectures/statistical-mechanics"
      type: lectures
    values:
      topic: "Statistical Mechanics"
  - scope:
      path: "_lectures/relativity"
      type: lectures
    values:
      topic: "Relativity"
  - scope:
      path: "_lectures/quantum-technologies"
      type: lectures
    values:
      topic: "Quantum Technologies"
  - scope:
      path: "_lectures/classical-mechanics"
      type: lectures
    values:
      topic: "Classical Mechanics"
  - scope:
      path: "_lectures/linear-algebra"
      type: lectures
    values:
      topic: "Linear Algebra"
  - scope:
      path: "_lectures/special-relativity"
      type: lectures
    values:
      topic: "Special Relativity"
  - scope:
      path: "_lectures/differential-geometry"
      type: lectures
    values:
      topic: "Differential Geometry"
  - scope:
      path: "_lectures/other-topics"
      type: lectures
    values:
      topic: "Other Topics"

